// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x961Ibudboq6j6O1UbzraNzSUzm6+oOkAShtkhUJhkfmxS2XK3bCt0Sz2S2uCZoup7",
	"h3OecD/JKV36rr7Y2MAk/jND3Lqum5aW1uVPx6VBSAkigjuHfzrcnaIAqj+PJ4gI+UfIaIiYwEj97DIE",
	"BfKO1acxZQEUzqHjQYG6AgfI6ThiHiLn0OGCYTJxHjuyi4eIwND/xHzZrdQCe7nRogh7toG4gCJSq0Ak",
	"CpzDfzmEiq5LCUGuQLLLPcQCk0l3TFk3nZY7HQcxRpnTcSZQTJEcsIsJlh+7mMwQEZTNnY4ThV1Bu3I3",
	"TsfhNGIu6k4oQc6XyuWckzG1bioKvUUhNUOMY0oswz12HIZ+jzBDnty3go8BR24hRWh3MgjLLimdK90Z",
	"HX1DrpDrULi/YvRhXiaAqRChwWOAyQdEJmLqHA46Dol8H4585BwKFqHi7jrOQ5fCEHdd6qEJIl30IBjs",
	"CjhRo86gjxXYDx0aYEGw34mY3+ECMsEJFfdYTI/k1FzBQv31zKsoLIHQBEDrXUEAH44G/X7feZTTlnHF",
	"OeI8WBWztmRFAgNkpXp6TxB7jxkXH00TD3GX4VAownYu5fe/cTCWTYAaplMxygfYNIgPa8YIEQswlzSu",
	"YIEFCnKygyGouGgKmezvIR8JO6ObHyBjcK4YfwrVp8M/nf/F0Ng5dP5rJ5WjO0aI7qSYGZoOsi+BIZ9S",
	"kV9T3TBD08O6EiWizluKT9X4Rv2cgiEr/thMUKrEpW5rgYZNEBkMZMbPi510z19qCfg9ZUGZiNMFNgDq",
	"PGlYSaDtuS/eZAcmy/uqxnx8GtjzhDxU3wAdAzFFIJ0KeFDAw1sC/jf4d7L/f4MuuIAkgj5IfgNR6FPo",
	"gRmG4Nfh5UfdBUr5LZufUt9XZyMYzcFliMhwiscCXOAJg3IJ4NibYU4ZUD1uidN5OsAoQXR8lK5QDa2F",
	"V5ZyykRTTxwfMBeteSYjFC1ck3691gRvJ7wx9i0oe499FEN9LCGXR5rTSSlihAlUfPVUmOoDxyoKpYAs",
	"088q8FgmfDsGFZjqcTdMBWaBt7n8hLwMp44o9REksZxF3kkj45vhh1Eyte75G5ZHclsxWxokTzZFwRev",
	"PDdZPRg+hRrGRRzq3yU1BWVU9pxOAWivghBK2zz1Iy4Qu9a9ZGsu/0aaa/NrNR9ACOcJH7nQdyMfSvUd",
	"uHoswDKDlcBgGmkpnB///G0MiXgkQZMJUG5YOfeqONSlRDDqX/mQoNOrT+V1nV59Ai5liIMQMWCag1C2",
	"B4R6CGx5aAwjXxyCN9vpqjARaILYgrojCkIx7wSYHO0qHXJXqZD5VV6gwBys+YXq3wEm4Oykea2DVS52",
	"Xy32YLBbWuxH6qFTGhELQX2MghFiEunlhfJDMACUgb3Mivfkgo0GNOjsfVnJ6vXBNwB7pZUP3SnyInMr",
	"KK792PfpPbin7E7xAtdtJRtQYttOZhtj6HOUgX1GdrphdDlD7JQGARbX8rDXM6uezqEzONxXSm+RPOkM",
	"sa6regGlI4At1Jv0OuBWdrl1MoBzBocDp+MMDnfVf/fVf9+UdUYJS9mlO4NMChAu+56G0SVBN/SSyDMk",
	"/tfNPc386z2NWOafQ/wgB1+KNaeUC+SdZnBikRpjoG5sBaBjDnRvgB4EYgT6/rwHzok8Q6DAIx8BeTUs",
	"9Bpj5HstcRUobmtA124JXYZJazG2W4+xdrjSE2XQlflBYyzzg0LasmiSXICYYvRm+akbK6Z4ivhJzrmy",
	"qEyX0yAot85Otte2prxETNd0M5VXWF4nDSXAhG5WXB7Ykqfu8OImPXkp2e6B8zEgVICQ0Rn2kNeRykQU",
	"IA4IVa234vGONCq2e+Ai4gKMELiN+v09dATyWOw4AXzAgSTA3X6/33ECTMw/V3/C9ctqaqonWKViFfsV",
	"idFCDV/aqkE8pIRbJM6pRc/JogMwxCO/WvcZ4j9a2CFOc40fO+mN+oYK6PPW92rTXMFX39tOKeFRYLbT",
	"oF+r6a8tHSsQZtZrn6y8iZbIGArKkHdOwsiiRuiPVvUzp6vCuMmTlFKrrfypKmRZ6qxO5Wsce1kNrUEZ",
	"W6c2tZDy9AzK0up1lUVVjnWrGCs95ld/SK/wiLUMXnk21YivVMoXrOAzxKDvJ+KKq3aAR0GgzU4F0VRg",
	"VL44k5ZBNYbYl9TROGDc0NxhoOchI0tnEPtwhH0s5tYphJTvVjpRkh+k1AJdRjkHEibVK1bDVVGKHjHI",
	"0Ev7MStAoIckCSDMHc6Qyd/zkN5uoMdaEGcojzeTXmbN+Rk6FkopIjqDlTxErWRMg9BHD1jM32J+N5S4",
	"ekeEDfyXBAEkP8ljSJ6UHuZ3wE36gxFD8M6j96RE3VwOaxElaV/VAowZDcAACAr2O+B+ihgCAyk25Ww+",
	"glzE0+m5x5SKkGEiACQe2I9bBjRt2ANqS2BwqBVg92jQBzcnWoPmmBLk/beZfDdpsiubxD/vJT8fZH/e",
	"Nz8j9Wsva50v0t4Q/4FuTqqIL7MSwAVlcIIkgG9OFAN+vuAACiCmmOuJsyZsj0bymE0m1nSs3qqDxpM+",
	"O7JbQEQzgcbN4onyW60ntMvhRxi0prIQse7lsCvvu1ZiK5tgKbc/TN5MEbgcqidJgB6gK/w5gBxgAWAY",
	"Isi4nHIW8B5Vz/X6GAW3zjXywC9QgHdEIBYyzBH4gEn0AP4Btt7sd0dYbN862z3LA81jpzXpQ87xhOi3",
	"oFNf/ms8vxz2QB8cgYjcEXpPOmAAjvJ80AH74ChP8BWU2JIiWESIPKcUWVwOe82UYKDdKZFEExEsJGsu",
	"h2uQNP2ipCEedqFANoFzOZSNA/U2h5S86WfaQyIbKEuTQVZmuU9EyeqY1IqRiAsaIGbxT6BEQDd55Lfe",
	"hqArrqaU2BugAGK7S5FPXSjsvjQ13gsRR6ziY2HjScvk+Tu7mcLS44VmllUHqIWeOhPoWh4630IBpcBH",
	"ZdDL0+3cswJhzBA6hSF0sZifnWSaZAhrCpl3Dxk6dl3kI0mw3gWdIfs7nrySWG/EylFpjDUhSoaQLQ2v",
	"KIL04g3IgxcKAeV1zmnysZH3G+ohO2GEjArqUj9+kC97eyjNpmH/oqr3DBGPsmb6EdpNojhZCfrJiJ0Y",
	"ZdXAL2wuhoKN1N4pd7gSVQSIczixSDfVHsSfm7xC4nZf5Exc4EDRvLzRogeLm1IIGdSEDj0Py6bQv8q1",
	"KGkfpQ1lPBcTtmlw5LENk672LRJGtuQhoX+XN+ykqTHTaYkPAcdk4qPEjkfLViIvYolwKsBZD4o8ELdR",
	"OloinRXzg62QSpU0nYEDSvy5uoY/QCnDnUNnb7rfD/rcpjEE8OFt5RIutLU23l92KVsMkgnymibeC3Yr",
	"5sWkZl5tFl5+3p+rpmUIciuwH+SlS09Bx2BK75UQyiD2Hqb2WOQ10r2ZyMZwZ4xGoe0EDEJI5vbTb3Hv",
	"vdz+bI62btWHdr5Md5h4WeexEDJBlCUTegEmVmNP9WG7qINsje+ZWpjZXyeBapX3ayWCTlXzBdC05DtX",
	"LZ6WHNOO2yUHWxjRSzuKmZGBHvdxha57lR5LhkqySEgoKMZ0JYkspJxprrdoZupD6g+0cmpLnsdWSW75",
	"QStlyVPxl53Gdkb/grmgEwYDLdFDhlwlnY0uWDhqoYA2paCky6W4CTD5DP0I2VtzgULbl6IKFA9ienT0",
	"Smxk9QvlNt/tMDqlDDXanpXps1olzr6hhNGQundINI7JTbM2o2KLYv+J4N8jBHCq3ydKjNTwraqBsh9e",
	"WGxYEjyxSRYTcHGStU9hIt7st1pn9Y2grcqeKOLVarW+0QhL2MREMry+BDVeXqqFrxtf9uTKJpEP649e",
	"07HltEtdftVaraAwcTEFq0uNDzImGq1aHufBp5yIz7DQr1WWZz/5HUywsqYEWIAp5NOcdugewMGbN4P9",
	"Nwdw92A0+MlFCI1++skbIHe/76HRwU/ezx7c329zu1Sr+awDaOyGQL0eE2Oj7IEdMIIceYAStUwBJ7nl",
	"9XuD3n53v9+dmIW2WcekGiBnqwFFVYiSfdefn7bfeqJLN5tfRQXxMWiRqfqljF8h9hYK6CIitFlqgdMh",
	"9zYch92U3y9lGzdpA9T7ag+cJncJADlQl39w7CujEPLA7PTqEwc7QFvtr6Zzjl3og1Mj4VsY5RN7Sfvw",
	"ktRGZNmslNZX9B6xoYACtbmilyGXYkWO1n5h6lisWJPEoHkdtSsBixz3hadwO06vjy/iQ2gZ1JquMW7N",
	"P83bp9/yyYUgcU/ZXXsQftQdbLvWhifDD3YYVrw1pZxTBWDZ6pcY1zaj9OrQZ3vU1FOXiTcDwByn2AVI",
	"JujILkTqmKGVO5UEZOnS7lzAUD3Am0d95YQJBAViijDLBP6YYJPSymepVFtoFabfV1zrujQ71aPbTgYz",
	"QCaI1X465IcCMMQ98J4yYA4HcOv83Ov39nr9W6fxUMisupNiphajb82NoBhlZk6MeqDJRu2B/NlASxN9",
	"Y+sLXt5fwJWvm5y3dlepK18BdQnBKN7gRhNHlR5sS7lbfL7g8TNaybltJb4Xi0wg4djohtFqQJt0kaMv",
	"5P5wHs72TykZY0v8k3HwPoMC3cN5zg6Gw9n+KqJ3cLj/FXoe03HEB9oeoENin2UuHB57HkP8+Wbk0Ygg",
	"cQH53UoCQPVwXwPI77SXcdmulO4xN3uniF8NeRuR/EpHZZo9ge6dvDcSD3yjIxNtOCduNuZQGTitN6ak",
	"je3pLQ1KA+dvwf0UETWFfgCWCguPXBdxPo60B2GjZRjFD0o170YAj/VG1ANKdfR5fohf6Qicv7Vd+m3G",
	"mThDRJ2g/ZWOhrphXV6FCjQNkynKy9Q9TdxuiIiHyeTfoAvkN8zB7xGKkGe+QsbN1yv9J7j+fEOpz8G7",
	"Bxf5YIx9pJsaojStr437xOXVMfh8AeKPlHDdOkGhbHxcIJQCYnUPjY54nfpf2tFAIdUMC4mL/Ew7/TRi",
	"flTuB4m5Qm/cUfYHrv9K92BsrGqJxq9M/ZGMZbVkfIAjbb3JE/kdWolNvuOr4SU1zAqWv6ePWSAxueR4",
	"GhuJXSCl7q8il0PiHZE0j90QypaE1DzVyOpLJDZZyrQUryn1nkhhUA25qiectsBYAtN6oMfafa7i+SID",
	"Gz1lNRQWeqUwJGe5JeovVe8UqwdpGtUTw9RmR0hMh6nP1dKhxkFihsw4P6UvwCuMOraOb8KPU7uYRwOI",
	"Sdf9eTVByQv5m1vhWhW7dFEPuOrQpaT1ifIHtnhYYH7X5fgPVPJH4x1AE7e9EDHjaeejGfLB1qC7v504",
	"47bx6U0cbWvcerm87DAFBU/iM+tLq0aTCz0EA7CVdf7d7oDd5Jdd88te8suB+WXf/KI9fLd74Nj3wZhG",
	"uY1xABkC0L+Hcw5ChjgiQvv7tfMPq/K+ttk2M7i5HFqs98MFUdLPo6St82OMmPb+jxpyeIbWArmcJ2kj",
	"3Oy28asmJ2NwmYOjh7nAxBWJP/FYXQTyd9a/8dQi1APvoDs1I7iQMWwAHQ+g5UgHYMHlRRgx7JbQCbb6",
	"//mf/7u/3VH+p7I3sTrv4mUBmfplW+AoGWqI/0DXSjYvaG4uhvJBgV3gU3oXhUDAkY9AAMNQLh5JOHmJ",
	"lBEYMaC0NUmCddDpgRsJe0qE1KgxNy+cLvTVuYJmSILeCH8JQIbGPnKFxsNbs7tErpAxnsQuTjFe0xlD",
	"6N7BCcq59qaymvIVAClLk8ZpOdnG5TBLcZjbSe6faK65rExoPOsBL6Zobnzg8y7w/w2UKpwOUkmZdvd1",
	"sJV3X+/ugyOAidQU1aUqHWZbYy+AocIgxIQXRFeJ5fLM1gEMTSDzfMR57C8WQDKPGSNhigKyimdw8QAs",
	"yd0yI2TxbRU3tcd56tR4Mrcf7dVH9CW3H9KnNBhhiY3L4d/fFqJ0JBwZHkXahU5K7BCx7ihy75DIqAha",
	"aB/kJbY6Mooyu62g0YtNt9tCYF9AwfBDHRM94cGr6DnqKs0BBGrOQ0AjKSfuYha6HJojVQOhAzAh2e9a",
	"3TAtBqpFhnfcGCG6Rc8mNJDNF7cOoGXn3TpqNrRiAW9L8lyBFi9voOvR39M5nk99z6JsqHBiCVrXuJKL",
	"ZRHpgc9yJEMZh+A2fvTqquf4W6cDbh0TBNal47EE562j0j7Iy5dQGR98HxgKUKQlh82f9o0pEptcuvUz",
	"X9E3RLfLuPkCNQ6SuKAzxBj2EDeHThBxITnJnQKjDRZ6maezOMRKMEj4GLGvUsH8GoxCrmEhYfN1SiPG",
	"v4aIffXgXP8umHqH5VNKxdcAE/15FuivIeXyV0MRXxGZYIIQ47fOdg984oh1eRSGPkYxJoCAd0gKNBd5",
	"iLhI7QeMqJgCYyTmSmNIztauhxieJf174JPRehN5wNA3ndtPidhfbm6uwH6/3+oIancNzDJm8zWwdPeT",
	"Asz1I08yqDwANEnFF8NEwUxQzEHEkafXXzA0pPy85KOrZpLchiLfIqPflS6wEt5a6TDrV5pBTFVtmGv7",
	"uWRxTuyVx6/F9TnnkUUVgLnsspYArSj3peQXWI7Lig259WZA3azj5DLZuZUhZvlttHeQKGzfIshiF4ry",
	"092M32PhThcLMBOF7KtcQOJB5mmdT2tNyhyeDN9xIiJlCWWiwjY+8yGpCOWaBfy0CkX2gCRSpU3adauy",
	"TfDZWPV95PtZoZPcpK0c2wPHI6lL6htOEMqrt1JIOdgywYvg6Aj07cxaHfNZqQTH1+nu/nav+q06vhO2",
	"C95WGqB5FU8esDE3OwFbHnJxAH1tS+r3+vphL2cBShVzzAE0IGE0UKI4vditNuJb6fa9pUO+M0CyUeaV",
	"9nLNKI8FGea6KKx/sGj0tHxypOpTnm+WjdZZLgY29jZuYFMD9aHJNpILs2oEJ9O4GrZ6rs3jN3657TgC",
	"sQAT+ETMtn+aUkDOvMGkbtn57SwZEdz0vJUHQ3WkUg2hPiGvaTVxL3uxsVP3k57fqgn+iTmX1xaK9PSg",
	"8TxZLPTuVxCcFu3HynrZyITkqT8WsoobvsX1OOof9fOjV70ypmKlpiDI4vKjePRUO30UJN1CMZxPDbhc",
	"QDIlFBXHPqq5bRuq0LCqgpGzlyGd/c5EOGsAl25raeqMJTXAUhC21XCdue+nb42lvQbwQelRzfHO2mXb",
	"En2ccUPMBCDnzD4H093KWGtMmhZgAp+fsoBB1QLKYWn51Vgg1Mlg0Eo++UzpZVdab7k7UauECXEIp910",
	"oVOlNaa1uyzms7M8U4dRy5x/7Xz3g/rcdEuNWrTqhFGSzbQGOtf23J1Fg6tuBNy0VUyHdd7DVrCljsNG",
	"UdKeX81A83GABV8ss+gH3acG5GVH4wWXRcv01by+IlE+EXsfEtBUIM7AbkEEJb2eQNJl+LYfdWGgxMVx",
	"VlL7aIlKM8WTOFNNp16d16VfLLfVuO5abX2TiSltko1EbIpC3Ir/EHCyrRLBIU9bCC4/Hyt/TinyfQq9",
	"djl2snP/BhmxJqk0H7IuwGZmmFuch8djxLi2RbgRY/Jjrkmra/raCl5he0RhGNcAa8SWrhYmlVY+vYpG",
	"Pnb/iRp7fjZXCW84/CXtpGwxGcNk7QhJQ6sr3XLFlZR1tr2VVTvvWq4X1VXEyBVDAea5l9ZMRqlVpg6p",
	"KpCXWUM1/1Zew+WfY+W6dDqFmLRG9Gmxo7wqE0n0Sbm5wvMfEkBQXV5APVj6CDKlKyraNIUIeuA3yeiS",
	"bQBl6VNfto16VFJP7myGPNnMgAMQCWHfz5oFM8hYCTUs4yPq4RnqWO/r7XhKYVBdvdPgygX4Kemjo3sq",
	"Knxp9HhTN8xjx/RN8GMacu23pMSyzsEvpWfC7jtxNw8KaJCaIDM/ZDt0xjd5uUAT+4BdezKBv5aoKxlb",
	"qpl4IaOJObct0kx/qUzqspEIr14ixB4IG8nwPUuGshSoCOnSv6uHMsCQiBjRzhix+5Ev78JQAI+Sv4m4",
	"BRVTxIAenJczB1dmWDwG0yiApMsQ9JS3auZz7JekjZT6X5gDOa72pFsk690xCKA7xQRVTnU/nRcmUL6u",
	"2hny1nkPsR8xdOuY9SjnIdVeQwdz88AqVCJPrErHZJK7pGkPeuAYXKtlAteHDI+xdvRWvixms5L7wSiS",
	"UFZFaETiCQSw6NWXibai08AyBZ5yvKbjQ3DrDHVw3K0jmSKz0x64UElIyZgeAlUD+HBnZ4JF7+5n3sNU",
	"0lwQESzmOyp3Oh5FgjK+46EZ8nc4nnQhc6dYIFdEDO1ooaYUakwJ7wXef/EQuV1IvG5S1LmswJboVh81",
	"NakK1P3pvO0FZ6WX33hq26kbh8W3sxyWVXfrmBex5eMka34u1K7OZg6rzT2SNIwf6mtSXbynTPuRxBVJ",
	"2rT7DYupuRvz+j4fqagf3hal7ljX1riQqlntEOd1rsNZX4NlHwJiN+gbnHtoLoULpU4NxgdhNLcHdilH",
	"hA5AhGF3GnvOabt7EsyjXMG1xwIYRiFiHHmI55yas27UVn+RbPK2+pQPZao1cRDpDHL3zw5BY+tVURIZ",
	"AAoc++lJGBeypWovSLDV7w76N/ikAwb97q7+a7ffPdB/HfT/foNPtivCGvTOo2YLWA3kdM7mJTvHwFox",
	"wK0blXohf8pEcoCGSaw0u2jMSDE9zxMZEGz1jz6lTm0dMDh6B/m8A3aPLpCHo6AD9o5+gczrgP2j3+S5",
	"eebTWbY4SuUWw6gJeU0xMTXMoEr9YMRSz7G4ClK/u6+dPw+6P+s//tEdvNF/DX7q7u3qP/d2/66LJTVs",
	"Qz8KrXEn5tWpcTO2Pex135jvbw66g12z38HuP7q7B6b57sGbdhv9iN2E21e5zdEcfDw/BcphNLMxs1Sz",
	"SLMf/b/9qgUnZJw9rVfkXEoy219CXpHsGa316FWujvKnyglL1FqcFnIZkWd62yRduLIkdQwGSx8gTZpi",
	"KzVxYR1RNtPFyN9ifseb/DPVlXUKZwhAYYJwKUFAVzFXB37LTEhOeVcZzSeGZHImZw/3PMIqKNnGe1ZF",
	"tNJSJu/bmHxAZCKmzuGg6QFpMYsTwX7HRUxoX6I6G9IqciF3NLnFFdgzE+asImvfMefTr3doXljCSvaa",
	"ZlwqbjWo9MJXeaSaLqxpAq7HKlWsqLKVJmpRZiu9QaTFtZRZRB6zKy2qFft9m4HbMKtZen2lnqJOuVIo",
	"qA/Gi2d1oKiQZmqy2E4W11qpB1P7OmPpKVa8/FZGw6QRHBXvmRMGPXSNXBoEiHiwyivHfFchB8D0UiC+",
	"uPkMMoEiKp+CBI0LCRihuKlKYQFBtlnjW6lroGILQskcwAzp8OxuxCyJmtBDiBniX6GwluHA2ejNOEPh",
	"p+sPQNA7pMybLfMMMUvFliuGuiZ0XA4ph48dHXQdMgSMz4yHuUtV9DsO4AT1GmEj5ytD41H7CygK8bGL",
	"TOCcfopwjkPoThHY7fUds2Antije39/3oPrco2yyY/rynQ/np+8+Dt91d3v93lQE+q0EC+X5V5dR+/jq",
	"PE2W7Bw6swH0wykcKCIOEYEhdg6dvV6/N1D+7GKqkLUDQ7wzG+ykwVc6hTmyIO8D5gJkG6qRjWbpmQbH",
	"ue9pwJ9z+K/ieO+xr5InpD1UII/Gj0oDJ8915/cIKTOjgan+rnJF8SRMtsHk+fhFlZZWcY1qf7v9fuxB",
	"b1xwYBj6WPte73wzxvR0/NrXjmT96nHxsVSFwbn8p8TCfn+wsjl1TSfLVJ8IjMSUMvwH8uSkByvcaOWk",
	"50QXINZJ5PTJq878f2WD+r4o3d0W8q09KwAkIBcDmCcu3eg428D48p1Qb74GbL6nLCg680vF6rFES4M1",
	"zG6DswaBp4npGfB6Aj2QiRjYEPBjxyYwd77REd/5E3uPmrR9JGwBhCo+AkDwjY7KxK0+/qq+1MrMNHGB",
	"HkZJSCnNUwGJPadIslZRWZVac63CUm6xRkL+IES9399b/6TvKRthz0NEz7i//hk/UvGeRsRs8R/rn1Be",
	"9XystdKXFhSSH+URZ1WdzpBQ6XCTJ988+58hseH9De9/L7z/Olix4rBmM0Gp9lhrr41qX/U4a/MY+0in",
	"554ySmjEVd5sm7pqerTUWoPIFziETOxIRu3G9cwWVR2v9Q7b66+762bxYxMxavJJuxs99nXxRJPu+lb9",
	"3nBB041ypN7yOMsN+oRT7UUv/5ujbXO0Pbs9pVLZVJbOELl4jFWVqkquPUNiw7Iblt2w7LOZQCMLy2r3",
	"3oYDVjd6rdy6TlOsCbRppcxuBMVGUPwVBMUQsRli4N1SFmepsO+YxAxdwxHJ413FtTatTmFS3mb76Wwv",
	"9Q8w8QApX5jCjtfZBXznQsmy5YQ1n1c8WVdicrfabKU2rCeJlSnJVIvaCLa/vmDLlAMjVOj8/i+mDclp",
	"nwHKUqRiF4FPJK22uzLJuqNzWXQxMRpc5d3LJL2wilnVuyxsM0l2aq5nFo4fqrnO1Zpei+TtVM/8+eJe",
	"JbBPdmvz8EhTVtet4jmvjA2At5FiCxpIXso2kvY7kbSU1WH85eXwUrIwiejp5hM+N6mZDeXWFhCCyZiW",
	"qmV/XX0zyeiXq1SRKSvx2GmJ/5oiec+sk9aVlbPQZ1NhuY1KulFJX5EoTCTa0pKwULJmkVu3pVTHdyz7",
	"bNVw/pUvweF8ydaeKdd8cQ4H/X6/Y6n64hy+eVxcuJZrF61MuGbAkaes/IaLCXevKBfdVIaeTpFrYsKS",
	"BLTOgckVG6cIkdymoin+D3jT7/VBgAnXVfJ2wKAPkuo2QM6LyQT8DKY7HpybdMA6gJ6OwQCYDDRzrvOq",
	"qEooqWN6YRl70/3iQiR2ev0+ODsBUIA3u31wMQo52NrdVavaOej3z062FaeWM/s6+9M9M2A5627y8bGq",
	"+EpKN1XVfST1dGqoqqpmkHP4ppLmYpLjFlp+IkG2OWMzcmdj99kcsn+hQ3ZnNM9kpnjakTti9A4RFRYE",
	"RvO0ll65rstCZ3Eu58J3bgN/jiNx6ZVY6162lYuaIOKbyEZKbqTkK5WSKoS/zmXvE1FNbG6sUvBEXJX3",
	"NXVtAGUTSPAf8a2i4Heghyo4sa6Jo5OaHZsH982D+zN75ryWM9uu3Awt/KyTmi3Iz8MNN2+4+Tvn5szZ",
	"6UZc0EBxdV1ge9JMWTqCeTtekl1PkwnW+QRpJmmKMd/w05r46aXJOy5BaKftnT/jaoW1gRzXKKAzBGBC",
	"7VojbEXqum9MhxW0viHK71LIg1cj5VM2aFDYYkIFmTKeFm0t83UBX5MMC04YjcKmpCm+D0w72wFyFn9q",
	"ky5lNNdDgTtMvAoPGvMp3UBSxDGpYwq9ABNLivey9046ry6H7kKOuphwRDgWeKaqugsMfV2hf7tiSQbG",
	"1TCtmdfUOVx26rRM4st4Dyn0bnLDlBU211R5b0wMoym+Isb2zHxbh6VTjW0K/zxzKhi9rU0WmFdGqiXJ",
	"3zp4toKI9eeYiFvaIOKh/lqRd5Uk/YJC8MfToLJit9KH2VCrPH1VJraSV/KGYDcE+xJ6Ql30ZIWE1Z9f",
	"F8GuSVV5mUDJRjb5Ye7/Py5r2vWinQAFo0bTq2kEMKnk4eSafGEG/M5PHr3NV3hp/MGPn/prqibkOjrO",
	"XFk1ir/jE0lv8GVuzwa4m+vzCzHtD5f+se1J2PKhxhgNJN8bocKQS5mXevCk2X3ULD1wglwY8YwYCiJl",
	"er6Hcw5GyKdkolPCq/adYtnHELEASjj4c6BXxbPT/+d//p9ylfomB01/51Mc6vpetseiVybnSibmTwYV",
	"8dRBvNSVPRRsXsk2GsQCF9hmBSJzmf3hGWtdKsvL3KKrVZaNgPgRr9HYQ0SYcAfr3flaVaHWp7SEoGyu",
	"arIl3oCMjrGPVNFmCHzqQh+YqQB6wFzwjillzeOkFbKnKSt+KaaI3WOOkjYQ8DkRU8QlpgBDk8iH+n29",
	"ZzMRn8cbWCPTJHNsnlabCcrUqak0+tfVl8kU9bbiWo69TjyraoBVOH5pcCvI5mBtHC2a/ELiNDVWDyy7",
	"s8hVPPLGY+F1+ODFqN4xCkmTsTP1LE061OD5Om2zNnTnp9rgfUm8ty8BEyKi6pEVCKGiLEwePQs5Xm60",
	"t9fkkniVR3emxtnKI0hst0ydhR9QuYBvyBVZN+AqCtRXIQsFrv7ulZ/kZe5ghY1u7mIbl+aXPl2aDpUP",
	"CM5Qy2AV2fQqcQF+5cfIhvCe8+CqvBRWREIBDwmIfWstq3oS+449szYk++p0Le3GuC5Nq0pgx3eCJNfQ",
	"yy6zMqQ4GgVY6oGFi0gPXBJ/nrPwcVVeOoB3SD8cxi0rPBxeQGN8GUeDZo3xx3Q42IjCF1EbdXVsXqcw",
	"enE8gkt9H7nqMKdjEPe0xycMk68vmCvgB7Q8aaxUa2jKpFiFOvnxORCnptiYDeuQ1+A4aFraz9Jh/HEd",
	"Z6ge/GXOTrOxzZn5uqi1fJy0j3GrIOTsIdLeYSUZ7K/lu11N1hvj4SbpzVpqRjWpCeWSkBWMeobEhks3",
	"XLrh0rUpgjX+nxU8qb++NrZclyr6Mg9/1dJArycRmBvJsJEMazy/K3TvHRzAidK7pwh6ZQHyC4Ke4vrL",
	"z8dAty1KEdnk3HypFyHey53sNQdxG/ZoRc7N5NdILouiV2OkAbvdiPm17pk5/IIZhuDT9YdqDe4tvSc+",
	"hZ5uVIty3QFg7y+nxYUMcTwhyFPQs8m06w9AUJXuXQIjwyAbl/q1ydVFSJ/MEBGU6az+NcpR2tCuH51n",
	"vn+3KlJxq69US8oga6MvbfSlNetLUwR9Ma08OvVn4E6Re2fTinzF9u20kcwSzKxf1Pq5WqiWNuoYd3ac",
	"xy+P/z8AAP//+PE1mHQnAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
